### ISSUE TITLE
Does not work when using 64-channel LiDAR

### ISSUE THREAD

**Issue by JihunDev** [heethesh/lidar_camera_calibration#12]
## Description of the situation
I am using Ouster OS1 64-Channel Lidar.
I am trying to calibration to my USB camera and Lidar. However, it outputs as below

![Picture1](https://i.imgur.com/8ZnX9pC.png)

## Question
I have 2 questions.
1. Does this code work on Velodyne devices?
2. Does it work only on 16 channels?

## Development environment
- ubuntu 18.04 LTS
- Python 2.7
- ROS
- MatplotChart 2.1.2

## Resources
[Ouster OS-1](https://ouster.com/products/os1-lidar-sensor/)

**Comment by heethesh** [comment]
Number of beams/sensors should not matter as long as the message format is `PointCloud2`. Just remove `c=cmap(colors)` on line 256 and try running it again. Also can you check the size of `points` wtihin `extract_points_3D`?

**Comment by saran1995** [comment]
Hey @JihunDev  my situtaiton is similar to yours:
1) We are using  Ouster OS1 64-Channel Lidar and we are trying to calibrate usb camera and Lidar. 

Once we run the command for calibration the gui doesn't not opens up, basically its stuck on rospy.spin
![Screenshot from 2020-10-23 15-34-51](https://user-images.githubusercontent.com/30192773/96990929-610b7680-1545-11eb-877a-822fc08d1f04.png)


**Development Environment** 
- ubuntu 18.04 LTS
- Python 2.7
- ROS
- MatplotChart 2.1.2


Please guide how did you solved this issue.

**Comment by heethesh** [comment]
@saran1995 also see #16
