### ISSUE TITLE
Error while running  calibrate_camera_lidar.py 

### ISSUE THREAD

**Issue by poornimajd** [heethesh/lidar_camera_calibration#14]
Hello great work @heethesh .
When I try to run  rosrun lidar_camera_calibration calibrate_camera_lidar.py --calibrate command  I got the following error. I tried to change the package.xml file also but it made no difference.

`ImportError: No module named tf2_sensor_msgs.tf2_sensor_msgs
`
Any suggestion is greatly appreciated.
Thank you

**Comment by heethesh** [comment]
`sudo apt install ros-melodic-tf2-sensor-msgs` (or `kinetic`, whatever ROS distro you have)

**Comment by poornimajd** [comment]
Thanks for the quick reply!It works
