### ISSUE TITLE
KITTI DATASET(left_camera and VLP64E)

### ISSUE THREAD

**Issue by enting8696** [heethesh/lidar_camera_calibration#28]
Thanks to the author for providing great code ！
I tried to use the kitti dataset (left_camera and VLP64E) .
May I ask why I changed the topic to /kitti/camera_gray_left/image_raw
And run  **roslaunch lidar_camera_calibration display_camera_lidar_calibration.launch** 
![Screenshot from 2021-02-02 14-39-53](https://user-images.githubusercontent.com/59861551/106562011-a556db80-6564-11eb-8121-1faae10152d5.png)
The result of the image does not cover the entire window ? it feels crooked.
![Screenshot from 2021-02-02 14-43-21](https://user-images.githubusercontent.com/59861551/106562269-0a123600-6565-11eb-934c-36e772f84031.png)
Does this algorithm apply to the left camera?

The display in rviz is normal
![Screenshot from 2021-02-02 14-47-05](https://user-images.githubusercontent.com/59861551/106562654-90c71300-6565-11eb-9df8-861d2f57cfa7.png)

**Comment by heethesh** [comment]
Make sure to set the field of view of the point cloud while projecting it. See the README for more details.

**Comment by enting8696** [comment]
Thank you for your intentions and replies, thank you, and wish you success in your research
