### ISSUE TITLE
Running command: "make -j4 -l4"

### ISSUE THREAD

**Issue by Shivaiitk** [heethesh/lidar_camera_calibration#30]
![Screenshot from 2021-02-16 12-58-56](https://user-images.githubusercontent.com/67453808/108031703-4eb6ca80-7057-11eb-941a-604dbe849c87.png)
Error is showing should i install something other dependencies.

**Comment by heethesh** [comment]
Where does `marker_6dof.h` come from? There's no C++ code in this package. Does another package you use have the same name? This doesn't seem to be an issue related to this repository or its setup.

**Comment by heethesh** [comment]
Feel free to reopen if you still think this might be an issue with this repository.
