### ISSUE TITLE
Error Camera-LiDAR Calibration GUI Demo

### ISSUE THREAD

**Issue by lemon5254** [heethesh/lidar_camera_calibration#4]
hi ~ thanks your package ! 
I have a question !
After I pick points, I get some error like that picture. 
How can i slove it? 
![lemon@vincent-Strix-GL703GS-GL703GS: ~-hee_calibration_ws_022](https://user-images.githubusercontent.com/58410528/78662372-d80f5380-7902-11ea-9ec7-76482d6854a8.png)

**Comment by heethesh** [comment]
It's an assert that has failed. You need pick the same number 2D/3D corresponding points. If the issue still persists, delete the pcl_corners.npy and img_corners.npy files (highlighted in yellow above) as they might have different number of points from previous runs.

**Comment by lemon5254** [comment]
OK!! THANKS
